# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OutputFileWindowClass.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1461, 203)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        Dialog.setFont(font)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.w_f_dec = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.w_f_dec.setFont(font)
        self.w_f_dec.setObjectName("w_f_dec")
        self.verticalLayout_2.addWidget(self.w_f_dec)
        self.w_f_exp = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.w_f_exp.setFont(font)
        self.w_f_exp.setObjectName("w_f_exp")
        self.verticalLayout_2.addWidget(self.w_f_exp)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.d_s_wl = QtWidgets.QSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.d_s_wl.setFont(font)
        self.d_s_wl.setMinimum(0)
        self.d_s_wl.setMaximum(16)
        self.d_s_wl.setProperty("value", 5)
        self.d_s_wl.setObjectName("d_s_wl")
        self.verticalLayout.addWidget(self.d_s_wl)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_9.addWidget(self.label_5)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setFlat(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_10.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.w_o_a = QtWidgets.QRadioButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.w_o_a.setFont(font)
        self.w_o_a.setObjectName("w_o_a")
        self.verticalLayout_10.addWidget(self.w_o_a)
        self.w_o_d = QtWidgets.QRadioButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.w_o_d.setFont(font)
        self.w_o_d.setObjectName("w_o_d")
        self.verticalLayout_10.addWidget(self.w_o_d)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem2)
        self.verticalLayout_9.addWidget(self.groupBox_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_9)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.i_f_dec = QtWidgets.QRadioButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.i_f_dec.setFont(font)
        self.i_f_dec.setObjectName("i_f_dec")
        self.verticalLayout_5.addWidget(self.i_f_dec)
        self.i_f_exp = QtWidgets.QRadioButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.i_f_exp.setFont(font)
        self.i_f_exp.setObjectName("i_f_exp")
        self.verticalLayout_5.addWidget(self.i_f_exp)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.d_s_int = QtWidgets.QSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.d_s_int.setFont(font)
        self.d_s_int.setMaximum(16)
        self.d_s_int.setProperty("value", 5)
        self.d_s_int.setObjectName("d_s_int")
        self.verticalLayout_3.addWidget(self.d_s_int)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setContentsMargins(0, 2, 0, -1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.t_w = QtWidgets.QRadioButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.t_w.setFont(font)
        self.t_w.setObjectName("t_w")
        self.verticalLayout_7.addWidget(self.t_w)
        self.t_n = QtWidgets.QRadioButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.t_n.setFont(font)
        self.t_n.setObjectName("t_n")
        self.verticalLayout_7.addWidget(self.t_n)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem6)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.separ_sign = QtWidgets.QPlainTextEdit(self.groupBox)
        self.separ_sign.setMaximumSize(QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.separ_sign.setFont(font)
        self.separ_sign.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.separ_sign.setObjectName("separ_sign")
        self.verticalLayout_8.addWidget(self.separ_sign)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem8)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_clear = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_clear.setFont(font)
        self.btn_clear.setObjectName("btn_clear")
        self.verticalLayout_4.addWidget(self.btn_clear)
        self.btn_close = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_close.setFont(font)
        self.btn_close.setObjectName("btn_close")
        self.verticalLayout_4.addWidget(self.btn_close)
        self.btn_save = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_save.setFont(font)
        self.btn_save.setObjectName("btn_save")
        self.verticalLayout_4.addWidget(self.btn_save)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.horizontalLayout.addWidget(self.groupBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.w_f_dec, self.w_f_exp)
        Dialog.setTabOrder(self.w_f_exp, self.i_f_dec)
        Dialog.setTabOrder(self.i_f_dec, self.i_f_exp)
        Dialog.setTabOrder(self.i_f_exp, self.t_w)
        Dialog.setTabOrder(self.t_w, self.t_n)
        Dialog.setTabOrder(self.t_n, self.btn_clear)
        Dialog.setTabOrder(self.btn_clear, self.btn_close)
        Dialog.setTabOrder(self.btn_close, self.btn_save)
        Dialog.setTabOrder(self.btn_save, self.separ_sign)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Format of the output file"))
        self.label.setText(_translate("Dialog", "Output format for wavelength"))
        self.w_f_dec.setText(_translate("Dialog", "decimal (0.12345)"))
        self.w_f_exp.setText(_translate("Dialog", "exponential (1.2345e-01)"))
        self.label_14.setText(_translate("Dialog", "digits number (up to 16)"))
        self.label_5.setText(_translate("Dialog", "Wavelength order"))
        self.w_o_a.setText(_translate("Dialog", "ascending"))
        self.w_o_d.setText(_translate("Dialog", "descending"))
        self.label_2.setText(_translate("Dialog", "Output format for intensity"))
        self.i_f_dec.setText(_translate("Dialog", "decimal (0.12345)"))
        self.i_f_exp.setText(_translate("Dialog", "exponential (1.2345e-01)"))
        self.label_8.setText(_translate("Dialog", "digits number (up to 16)"))
        self.label_3.setText(_translate("Dialog", "Add column names?"))
        self.t_w.setText(_translate("Dialog", "with column names"))
        self.t_n.setText(_translate("Dialog", "no column names"))
        self.label_4.setText(_translate("Dialog", "Separator between\n"
"wavelength and intensity"))
        self.label_7.setText(_translate("Dialog", "(default value is Tab)"))
        self.btn_clear.setText(_translate("Dialog", "Clear this form"))
        self.btn_close.setText(_translate("Dialog", "Close without change"))
        self.btn_save.setText(_translate("Dialog", "Save and Close"))
