# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReferenceWindowClass.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1561, 399)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        Dialog.setFont(font)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_13.addWidget(self.label_6)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.groupBox)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_upload_wth = QtWidgets.QPushButton(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.btn_upload_wth.setFont(font)
        self.btn_upload_wth.setObjectName("btn_upload_wth")
        self.verticalLayout_4.addWidget(self.btn_upload_wth)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_wth_file = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.label_wth_file.setFont(font)
        self.label_wth_file.setObjectName("label_wth_file")
        self.horizontalLayout_6.addWidget(self.label_wth_file, 0, QtCore.Qt.AlignTop)
        self.del_wth_file = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_wth_file.sizePolicy().hasHeightForWidth())
        self.del_wth_file.setSizePolicy(sizePolicy)
        self.del_wth_file.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.del_wth_file.setFont(font)
        self.del_wth_file.setObjectName("del_wth_file")
        self.horizontalLayout_6.addWidget(self.del_wth_file, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 5, 0, 1, 1)
        self.wth_separator = QtWidgets.QPlainTextEdit(self.tab_3)
        self.wth_separator.setMaximumSize(QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.wth_separator.setFont(font)
        self.wth_separator.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.wth_separator.setObjectName("wth_separator")
        self.gridLayout_3.addWidget(self.wth_separator, 5, 1, 1, 1)
        self.top_column = QtWidgets.QSpinBox(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.top_column.setFont(font)
        self.top_column.setMinimum(1)
        self.top_column.setProperty("value", 3)
        self.top_column.setObjectName("top_column")
        self.gridLayout_3.addWidget(self.top_column, 4, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 4, 0, 1, 1)
        self.wth_start = QtWidgets.QSpinBox(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.wth_start.setFont(font)
        self.wth_start.setMinimum(1)
        self.wth_start.setMaximum(999)
        self.wth_start.setObjectName("wth_start")
        self.gridLayout_3.addWidget(self.wth_start, 2, 1, 1, 1)
        self.wth_column = QtWidgets.QSpinBox(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.wth_column.setFont(font)
        self.wth_column.setMinimum(1)
        self.wth_column.setProperty("value", 2)
        self.wth_column.setObjectName("wth_column")
        self.gridLayout_3.addWidget(self.wth_column, 3, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 2, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 6, 0, 1, 1, QtCore.Qt.AlignTop)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.wth_max = QtWidgets.QLineEdit(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.wth_max.setFont(font)
        self.wth_max.setObjectName("wth_max")
        self.gridLayout_4.addWidget(self.wth_max, 1, 2, 1, 1)
        self.wth_min = QtWidgets.QLineEdit(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.wth_min.setFont(font)
        self.wth_min.setObjectName("wth_min")
        self.gridLayout_4.addWidget(self.wth_min, 0, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 1, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 0, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 2, 0, 1, 1)
        self.top_min = QtWidgets.QLineEdit(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.top_min.setFont(font)
        self.top_min.setObjectName("top_min")
        self.gridLayout_4.addWidget(self.top_min, 2, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 3, 0, 1, 1)
        self.top_max = QtWidgets.QLineEdit(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.top_max.setFont(font)
        self.top_max.setObjectName("top_max")
        self.gridLayout_4.addWidget(self.top_max, 3, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.top_const = QtWidgets.QLineEdit(self.tab_5)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.top_const.setFont(font)
        self.top_const.setObjectName("top_const")
        self.gridLayout_6.addWidget(self.top_const, 1, 1, 1, 1)
        self.wth_constant = QtWidgets.QLineEdit(self.tab_5)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.wth_constant.setFont(font)
        self.wth_constant.setObjectName("wth_constant")
        self.gridLayout_6.addWidget(self.wth_constant, 0, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_6.addWidget(self.label_20, 1, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayout_6.addWidget(self.label_31, 0, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_6)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.verticalLayout_13.addWidget(self.tabWidget_2)
        self.gridLayout_2.addLayout(self.verticalLayout_13, 0, 10, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_upload_wl = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.btn_upload_wl.setFont(font)
        self.btn_upload_wl.setObjectName("btn_upload_wl")
        self.verticalLayout_2.addWidget(self.btn_upload_wl)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_wl_file = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.label_wl_file.setFont(font)
        self.label_wl_file.setObjectName("label_wl_file")
        self.horizontalLayout_5.addWidget(self.label_wl_file, 0, QtCore.Qt.AlignTop)
        self.del_wl_file = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_wl_file.sizePolicy().hasHeightForWidth())
        self.del_wl_file.setSizePolicy(sizePolicy)
        self.del_wl_file.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.del_wl_file.setFont(font)
        self.del_wl_file.setObjectName("del_wl_file")
        self.horizontalLayout_5.addWidget(self.del_wl_file, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.wl_separator = QtWidgets.QPlainTextEdit(self.tab)
        self.wl_separator.setMaximumSize(QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.wl_separator.setFont(font)
        self.wl_separator.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.wl_separator.setObjectName("wl_separator")
        self.gridLayout.addWidget(self.wl_separator, 2, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 0, 1, 1)
        self.wl_column = QtWidgets.QSpinBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.wl_column.setFont(font)
        self.wl_column.setMinimum(1)
        self.wl_column.setObjectName("wl_column")
        self.gridLayout.addWidget(self.wl_column, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 1)
        self.wl_start = QtWidgets.QSpinBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.wl_start.setFont(font)
        self.wl_start.setMinimum(1)
        self.wl_start.setMaximum(999)
        self.wl_start.setObjectName("wl_start")
        self.gridLayout.addWidget(self.wl_start, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1, QtCore.Qt.AlignTop)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 0, 1, 1)
        self.wl_min = QtWidgets.QLineEdit(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.wl_min.setFont(font)
        self.wl_min.setObjectName("wl_min")
        self.gridLayout_5.addWidget(self.wl_min, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 1, 0, 1, 1)
        self.wl_max = QtWidgets.QLineEdit(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.wl_max.setFont(font)
        self.wl_max.setObjectName("wl_max")
        self.gridLayout_5.addWidget(self.wl_max, 1, 1, 1, 1)
        self.wl_step = QtWidgets.QLineEdit(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.wl_step.setFont(font)
        self.wl_step.setObjectName("wl_step")
        self.gridLayout_5.addWidget(self.wl_step, 2, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_5)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_8.addWidget(self.tabWidget)
        self.gridLayout_2.addLayout(self.verticalLayout_8, 0, 3, 1, 1)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.btn_clear = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_clear.setFont(font)
        self.btn_clear.setObjectName("btn_clear")
        self.verticalLayout_12.addWidget(self.btn_clear)
        self.btn_close = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_close.setFont(font)
        self.btn_close.setObjectName("btn_close")
        self.verticalLayout_12.addWidget(self.btn_close)
        self.btn_save = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_save.setFont(font)
        self.btn_save.setObjectName("btn_save")
        self.verticalLayout_12.addWidget(self.btn_save)
        self.gridLayout_2.addLayout(self.verticalLayout_12, 0, 12, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 0, 9, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 0, 11, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 0, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 0, 4, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_9.setContentsMargins(0, 2, 0, -1)
        self.verticalLayout_9.setSpacing(7)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_cm = QtWidgets.QRadioButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cm.sizePolicy().hasHeightForWidth())
        self.btn_cm.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.btn_cm.setFont(font)
        self.btn_cm.setText("")
        self.btn_cm.setObjectName("btn_cm")
        self.horizontalLayout_2.addWidget(self.btn_cm)
        self.cm_label = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cm_label.sizePolicy().hasHeightForWidth())
        self.cm_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.cm_label.setFont(font)
        self.cm_label.setObjectName("cm_label")
        self.horizontalLayout_2.addWidget(self.cm_label, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.rbtn_micron = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.rbtn_micron.setFont(font)
        self.rbtn_micron.setObjectName("rbtn_micron")
        self.verticalLayout_9.addWidget(self.rbtn_micron)
        self.rbtn_nm = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.rbtn_nm.setFont(font)
        self.rbtn_nm.setObjectName("rbtn_nm")
        self.verticalLayout_9.addWidget(self.rbtn_nm)
        self.rbtn_A = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.rbtn_A.setFont(font)
        self.rbtn_A.setObjectName("rbtn_A")
        self.verticalLayout_9.addWidget(self.rbtn_A)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_9.addWidget(self.label_13)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem9)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_10.addWidget(self.label_2)
        self.groupBox_c = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_c.setTitle("")
        self.groupBox_c.setFlat(True)
        self.groupBox_c.setObjectName("groupBox_c")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_c)
        self.verticalLayout_11.setContentsMargins(0, 2, 0, -1)
        self.verticalLayout_11.setSpacing(7)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.rbtn_Gaussian = QtWidgets.QRadioButton(self.groupBox_c)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.rbtn_Gaussian.setFont(font)
        self.rbtn_Gaussian.setCheckable(True)
        self.rbtn_Gaussian.setObjectName("rbtn_Gaussian")
        self.verticalLayout_11.addWidget(self.rbtn_Gaussian)
        self.rbtn_Triangle = QtWidgets.QRadioButton(self.groupBox_c)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.rbtn_Triangle.setFont(font)
        self.rbtn_Triangle.setCheckable(True)
        self.rbtn_Triangle.setObjectName("rbtn_Triangle")
        self.verticalLayout_11.addWidget(self.rbtn_Triangle)
        self.rbtn_Trapeze = QtWidgets.QRadioButton(self.groupBox_c)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.rbtn_Trapeze.setFont(font)
        self.rbtn_Trapeze.setCheckable(True)
        self.rbtn_Trapeze.setObjectName("rbtn_Trapeze")
        self.verticalLayout_11.addWidget(self.rbtn_Trapeze)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem10)
        self.verticalLayout_10.addWidget(self.groupBox_c)
        self.gridLayout_2.addLayout(self.verticalLayout_10, 0, 5, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_2)
        self.horizontalLayout.addWidget(self.groupBox)

        self.retranslateUi(Dialog)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.rbtn_Gaussian, self.rbtn_Triangle)
        Dialog.setTabOrder(self.rbtn_Triangle, self.rbtn_Trapeze)
        Dialog.setTabOrder(self.rbtn_Trapeze, self.tabWidget)
        Dialog.setTabOrder(self.tabWidget, self.btn_upload_wl)
        Dialog.setTabOrder(self.btn_upload_wl, self.wl_start)
        Dialog.setTabOrder(self.wl_start, self.wl_column)
        Dialog.setTabOrder(self.wl_column, self.wl_min)
        Dialog.setTabOrder(self.wl_min, self.wl_max)
        Dialog.setTabOrder(self.wl_max, self.wl_step)
        Dialog.setTabOrder(self.wl_step, self.btn_cm)
        Dialog.setTabOrder(self.btn_cm, self.rbtn_micron)
        Dialog.setTabOrder(self.rbtn_micron, self.rbtn_nm)
        Dialog.setTabOrder(self.rbtn_nm, self.rbtn_A)
        Dialog.setTabOrder(self.rbtn_A, self.tabWidget_2)
        Dialog.setTabOrder(self.tabWidget_2, self.btn_upload_wth)
        Dialog.setTabOrder(self.btn_upload_wth, self.wth_start)
        Dialog.setTabOrder(self.wth_start, self.wth_column)
        Dialog.setTabOrder(self.wth_column, self.top_column)
        Dialog.setTabOrder(self.top_column, self.wth_min)
        Dialog.setTabOrder(self.wth_min, self.wth_max)
        Dialog.setTabOrder(self.wth_max, self.top_min)
        Dialog.setTabOrder(self.top_min, self.top_max)
        Dialog.setTabOrder(self.top_max, self.wth_constant)
        Dialog.setTabOrder(self.wth_constant, self.top_const)
        Dialog.setTabOrder(self.top_const, self.btn_clear)
        Dialog.setTabOrder(self.btn_clear, self.btn_close)
        Dialog.setTabOrder(self.btn_close, self.btn_save)
        Dialog.setTabOrder(self.btn_save, self.del_wl_file)
        Dialog.setTabOrder(self.del_wl_file, self.del_wth_file)
        Dialog.setTabOrder(self.del_wth_file, self.wl_separator)
        Dialog.setTabOrder(self.wl_separator, self.wth_separator)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Destination wavelengths and parameters of the convolution function"))
        self.label_6.setText(_translate("Dialog", "Full Width at Half Maximum (FWHM)\n"
"and top width (for Trapeze function)"))
        self.btn_upload_wth.setText(_translate("Dialog", "Choose width and top file"))
        self.label_wth_file.setText(_translate("Dialog", "no file selected"))
        self.del_wth_file.setText(_translate("Dialog", "Clear the selected file"))
        self.label_16.setText(_translate("Dialog", "Columns separated by"))
        self.label_22.setText(_translate("Dialog", "Tops in column"))
        self.label_17.setText(_translate("Dialog", "Data starts at line"))
        self.label_15.setText(_translate("Dialog", "Widths in column"))
        self.label_5.setText(_translate("Dialog", "(default value is Tab)"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("Dialog", "Upload from file"))
        self.label_19.setText(_translate("Dialog", "End width"))
        self.label_18.setText(_translate("Dialog", "Start width"))
        self.label_23.setText(_translate("Dialog", "Start top"))
        self.label_24.setText(_translate("Dialog", "End top"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("Dialog", "Generate"))
        self.label_20.setText(_translate("Dialog", "Top"))
        self.label_31.setText(_translate("Dialog", "Width"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("Dialog", "Constant"))
        self.label_4.setText(_translate("Dialog", "Destination wavelengths"))
        self.btn_upload_wl.setText(_translate("Dialog", "Choose destination wavelength file"))
        self.label_wl_file.setText(_translate("Dialog", "no file selected"))
        self.del_wl_file.setText(_translate("Dialog", "Clear the selected file"))
        self.label_12.setText(_translate("Dialog", "Columns separated by"))
        self.label_11.setText(_translate("Dialog", "Wavelengths in column"))
        self.label_10.setText(_translate("Dialog", "Data starts at line"))
        self.label_3.setText(_translate("Dialog", "(default value is Tab)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Upload from file"))
        self.label_9.setText(_translate("Dialog", "Step"))
        self.label_7.setText(_translate("Dialog", "Start value"))
        self.label_8.setText(_translate("Dialog", "End value"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Generate"))
        self.btn_clear.setText(_translate("Dialog", "Clear this form"))
        self.btn_close.setText(_translate("Dialog", "Close without change"))
        self.btn_save.setText(_translate("Dialog", "Validate and Close"))
        self.label.setText(_translate("Dialog", "Wavelength unit"))
        self.cm_label.setText(_translate("Dialog", "cm-1"))
        self.rbtn_micron.setText(_translate("Dialog", "µm"))
        self.rbtn_nm.setText(_translate("Dialog", "nm"))
        self.rbtn_A.setText(_translate("Dialog", "Å"))
        self.label_13.setText(_translate("Dialog", "will be the unit for\n"
"the convolution result"))
        self.label_2.setText(_translate("Dialog", "Convolution function"))
        self.rbtn_Gaussian.setText(_translate("Dialog", "Gaussian"))
        self.rbtn_Triangle.setText(_translate("Dialog", "Triangle"))
        self.rbtn_Trapeze.setText(_translate("Dialog", "Trapeze"))
